version: 2
updates:
- package-ecosystem: pip
  directory: /
  schedule:
    interval: daily
  labels:
  - enhancement
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: daily
  labels:
  - enhancement
- package-ecosystem: docker
  directory: /
  schedule:
    interval: daily
  labels:
  - enhancement
