repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: debug-statements
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: detect-private-key
    -   id: fix-encoding-pragma
    -   id: check-docstring-first
    -   id: check-byte-order-marker
    -   id: check-json
    -   id: check-yaml
    -   id: mixed-line-ending
    -   id: check-ast
