name: Labels Check
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
  workflow_dispatch:

jobs:

  check_labels:
    name: Check labels
    runs-on: ubuntu-latest
    steps:
      - name: Label Checker
        id: label_checker
        uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          one_of: release
          repo_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: bcgov-nr/action-pr-description-add@main
        if: ${{steps.label_checker.conclusion}}
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          limit_to_pr_opened: "false"
          add_markdown: |
            ---
            ## Label Checker status Failed
            If the Label Checker status is `failure`, you forgot to add a label to the PR.
            - `Unrelease` label for those features not deployed yet
            - `Release` label for those features already released
            ${{ steps.label_checker.outcome }}
