name: Labels Check
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
  workflow_dispatch:

jobs:

  check_labels:
    name: Check labels
    runs-on: ubuntu-latest
    steps:
      - name: Label Checker
        id: label_checker
        uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          one_of: release
          repo_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: bcgov-nr/action-pr-description-add@main
        if: always()
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          limit_to_pr_opened: "false"
          add_markdown: |
            ---
            ${{ steps.label_checker.conclusion }}
            # Things!
            ## Excitement!
            [Links!](https://google.ca)
            `Code!`
            _Italics_
            *Bold*
            * Bullets!
            * and [more reading!](https://github.github.com/gfm/)
