name: Labels Check
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
  workflow_dispatch:

jobs:

  check_labels:
    name: Check labels
    runs-on: ubuntu-latest
    steps:
      - name: Label Checker
        id: label_checker
        uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          one_of: Released, Unrelease, bug_fix, enhancement
          repo_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check PR
        id: checker
        if: always()
        uses: JJ/github-pr-contains-action@releases/v14.1
        with:
          github-token: ${{github.token}}
          bodyContains: "Updated"

      - name: Get PR description
        if: ${{ steps.checker.outputs.conclusion == 'false'}}
        id: get_pr
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if PR description has been updated before
        if: ${{ steps.checker.outcome == 'success'}}
        id: check_description
        run: |
          description="${{ steps.get_pr.outputs.data }}"
      - uses: bcgov-nr/action-pr-description-add@main
        if: always()
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          limit_to_pr_opened: "false"
          add_markdown: |
            ---
            ## :shipit: Label Checker status Failed
            outcome: ${{ steps.checker.outcome}}
            conclusion: ${{ steps.checker.outputs.conclusion }}
            If the Label Checker status is `failure`, you forgot to add a label to the PR.
            - `Unrelease` label for those features not deployed yet.
            - `Released` label for those features already released.
            - `bug_fix`  label for any fix of an existing test case, module, or component.
            - `enhancement` label for any addition that is not test case related, for example, some reusable function or module.

            > [!WARNING]
            > PR without a label won't be merged, team members responsible for merging are not responsible for the status, it will be up to each owner to tag PR and change those tags if needed.

            > [!TIP]
            > Helpful advice for doing things better or more easily.

            --Updated--
