name: Labels Check
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
  workflow_dispatch:

jobs:

  check_labels:
    name: Check labels
    runs-on: ubuntu-latest
    steps:

      - name: Check PR
        id: checker
        if: always()
        uses: JJ/github-pr-contains-action@releases/v14.1
        with:
          github-token: ${{github.token}}
          bodyContains: "Updated missing label"

      - name: Label Checker
        id: label_checker
        if: always()
        uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          one_of: Released, Unrelease, bug_fix, enhancement
          repo_token: ${{ secrets.GITHUB_TOKEN }}


      - name: check response
        id: check_response
        if: always()
        run: |
          echo "response conclusion ${{steps.checker.conclusion}}"
          echo "response label checker ${{ steps.label_checker.conclusion}}"
          echo "${{ steps.label_checker.conclusion == 'failure'}}"

      - name: trigger by conclusion failure
        if: (failure() && steps.checker.conclusion)
        run: |
          echo "conclusion give failure steps.checker.conclusion => ${{steps.checker.conclusion}}"

      - uses: bcgov-nr/action-pr-description-add@main
        if: steps.checker.conclusion == 'failure' && steps.label_checker.conclusion == 'failure'
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          limit_to_pr_opened: "true"
          add_markdown: |
            ---
            ## :shipit: Label Checker status Failed
            outcome: ${{ steps.checker.outcome}}
            conclusion: ${{ steps.checker.outputs.conclusion }}
            If the Label Checker status is `failure`, you forgot to add a label to the PR.
            - `Unrelease` label for those features not deployed yet.
            - `Released` label for those features already released.
            - `bug_fix`  label for any fix of an existing test case, module, or component.
            - `enhancement` label for any addition that is not test case related, for example, some reusable function or module.

            > [!WARNING]
            > PR without a label won't be merged, team members responsible for merging are not responsible for the status, it will be up to each owner to tag PR and change those tags if needed.

            > [!TIP]
            > Helpful advice for doing things better or more easily.

            --Updated missing label--
