name: upload docker

on: 
  pull_request:
    types: [closed]
    branches:
      - main
  workflow_dispatch:

jobs:
  update_documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2

      - name: Build docker
        run: |
          docker build -t metals .
      
      # - name: Save Docker Image to .tar
      #   run: |
      #     docker save -o my-docs-image.tar mydocs

      # - name: Upload Docker image
      #   uses: actions/upload-artifact@v2
      #   with:
      #       name: my-docs-image
            # path: my-docs-image.tar
      - name: Log in to GitHub Packages Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Tag Docker Image
        run: docker tag mydocs ghcr.io/${{ github.repository_owner }}/${{ github.repository_name }}/mydocs:latest

      - name: Push Docker Image to GitHub Packages Container Registry
        run: docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository_name }}/mydocs:latest
