name: Update version

on:
  workflow_dispatch:

jobs:
  update_documentation:
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout
      #   uses: actions/checkout@v4.1.2

      - name: Get Current Version
        id: get_version
        run: |
          git fetch --tags
          latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "Latest tag: $latest_tag"
          version=${latest_tag#v} # remove 'v' prefix if present
          echo "::set-output name=version::$version"

      - name: Increment Version
        id: increment_version
        run: |
          version=${{ steps.get_version.outputs.version }}
          new_version=$(semver bump patch $version)
          echo "::set-output name=new_version::$new_version"
